config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :confirmations => "confirmations",
                                       :passwords => "passwords",
                                       :sessions => "sessions" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'
  get '/triggers_test/', :to => 'triggers_test#triggers_test'

  root 'home#index'
  resources :brands
  resources :users, except: [:destroy, :index] do
    member do
      get :favorites
      get :goods
      patch :set_password
      delete :destroy_social_account
      delete :delete_avatar
    end
  end
  resources :products, except: [:index] do
    collection do
      post 'get_subcategories'
      post 'get_details'
      get 'fake_typing_titles'
      get 'dynamic_admin_subcategory'
    end
  end

  resources :categories, only: [:show]

  resources :photos, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

  resources :shops, :controller => :shops do
    collection do
      post :update_shop_cover
      get :delete_shop_cover
    end
  end

  resources :promo_items, only: [:create, :update, :show] do
    member do
      get 'notify'
    end
  end

  controller :payments do
    post 'notify', as: :notify
  end

  post '/liqpay_payment' => 'payments#liqpay_payment'

  resources :conversations, only: [:index, :show, :create, :destroy]

  controller :static do
    get 'about', as: :about
    get 'condition', as: :condition
    get 'faq', as: :faq
    get 'contacts', as: :contacts
    get 'why_muzpoint', as: :why_muzpoint
    get 'how_advertising_works', as: :how_advertising_works
    get 'terms_of_use', as: :terms_of_use
  end

  resources :subscribers, :only => [:create]
  resources :feedbacks, :only => [:create]
  post 'mark_as_read',to:'messages#mark_as_read'
  resources :posts,path: :blog do
    collection do
      get 'articles'
      get 'photos'
      get 'overviews'
      get 'lessons'
    end
  end
  devise_scope :user do
    post 'session_path',to: 'sessions#path'
  end
  post '/switch_currency',to: 'switch_currency#switch'

  get 'template',to: 'xml_templates#template'
  get '/countries', to: 'countries#index', as: :countries, controller: "countries"
  get '/countries/:id', to: 'countries#show', as: :country, controller: "countries"

  get '/cities', to: 'cities#index', as: :cities, controller: "cities"
  get '/countries/:country_id/:state_id/:id', to: 'cities#show', as: :city, controller: "cities"

  get '/categories/:category_id/:id', to: 'subcategories#show', as: :subcategory, controller: "subcategories"

  get '404', :to => 'errors#page_not_found'
  get '500', :to => 'errors#server_error'
  get '/:category_id/:id', to: redirect("/categories/%{category_id}/%{id}", status: 301)
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :user

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true
  validates :title, length: { minimum: 3, maximum: 30 }
  # validates :title, uniqueness: true

  validates :site, format: {with: /\A[A-Za-z0-9._%+-]+\.[A-Za-z]+\z/, allow_blank: true}

  has_and_belongs_to_many :payment_types
  accepts_nested_attributes_for :payment_types

  has_many :products, dependent: :destroy

  has_attached_file :cover, :styles => { :medium => "940x200#" }, :default_url =>  "bg/bg_main_pic.png"
  validates_attachment :cover,
                              content_type: { content_type: /^image\/(jpeg|jpg|png|gif)$/ },
                              size: { in: 0..5.megabytes }


  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
  
  def count_of_products
    products.count
  end
end

app/helpers/shop_helper.rb
module ShopHelper
  def count_products_of_shop(count)
    count.to_s << ' ' << Russian.p(count, 'объявление', 'объявления', 'объявлений')
  end
end

app/views/shops/_flash_for_shop.slim
.flash-message id="flash__open" style="display:none"
  .flash-message__inner
    | Информация о Вашем магазине успешно сохранена
    a.flash-message__close id="flash__close"
      i.icon-cancel

app/views/shops/_shop_blank.slim
.header-top
  .layout-page
    h1.header-top__title
      = @shop.title.blank? ? "Продавец " + current_user.name : @shop.title

    - if current_user
      - unless @shop.user_id == current_user.id
        = link_to conversations_path(user_id: @shop.user.id), method: :post, class: "header-top__link"
          i.icon-mail
          | Связаться
    - else
      a#login_button_three.header-top__link href=""
        i.icon-mail
        | Связаться
.header-bottom
  .layout-page
    .main-pic style="background-image: url('#{image_path @shop.cover.url(:medium)}')"
    .header-bottom__title
      |На Музточке с
      =<l @shop.created_at.to_date, format: :long
    .header-bottom__text.pre-text
      - if current_user && @shop.user_id == current_user.id
        | Напишите что-нибудь о вашем магазине

    .header-bottom__btn
      - if current_user && @shop.user_id == current_user.id
        = link_to "Настроить магазин", edit_shop_path(current_user.shop), class: "button button_type_default"
.layout-page
  .no_product
    i.icon-tag.no_product-icon
    p.no_product-text Нет товаров на продажу
    - if current_user && @shop.user_id == current_user.id
      = link_to "добавить товар", new_product_path, class: 'button button_type_default'

app/views/shops/edit.slim
script src="https://maps.googleapis.com/maps/api/js?v=3&language=ru&region=RU&libraries=places&sensor=false"
= render 'users/profile_menu'
.layout-small
  .shop-top__title
    | Обложка магазина

- if @shop.errors[:cover].blank?
  .layout-page
    .main-pic style="background: url('#{image_path @shop.cover.url(:medium) }')"

- else
  .layout-small
    .shop-top__title
      ul
        - @shop.errors[:cover].each do |msg|
          li style="color:#ed6250"
            =< msg

.layout-small
  .shop-top__btn
    a#cover_button.button.button_type_default.button_size_small href=""  Сменить обложку
    input id='shop_cover' type='file' name='shop[cover]' style='overflow: hidden;display:none;' accept='image/jpg,image/png,image/pjpeg,image/jpeg'
    = link_to 'Удалить обложку', delete_shop_cover_shops_path, class: "button button_type_default button_size_small" if @shop.cover.present?
  .shop-top__text
    | Рекомендуемый размер обложки 940x200 пкс
    br/
    | Размеры больше или меньше указаных будут обрезаны
    br/
    | Поддерживаемые форматы изображения: PNG, JPG, GIF
    br/
    | Размер изображений не должен превышать 5 мб
    br/
  = form_for @shop, :html => {:class => "form form_shop"} do |f|
    .form-section
      .grid.clearfix
        .grid-item
          .form__label * Название магазина
          - if @shop.errors[:title][0]
            .inputbox.inputbox_error
              = f.text_field :title, class: "inputbox__input"
              .inputbox__error
                = @shop.errors[:title].last
          - else
            .inputbox
              = f.text_field :title, class: "inputbox__input", placeholder: "Введите название магазина"

    .form-section
      .grid.clearfix
        .grid-item.grid-about
          .form__label Краткое описание магазина
          .inputbox.inputbox_type_textarea
            = f.text_area :description, class: "inputbox__input"

        .grid-item
          .form__label Сайт
          - if @shop.errors[:site][0]
            .inputbox.inputbox_error
              = f.url_field :site, class: "inputbox__input"
              .inputbox__error
                = @shop.errors[:site].last
          - else
            .inputbox
              = f.url_field :site, class: "inputbox__input"

    .form-section
      .grid.grid_cols_2.grip_inside.clearfix
        .grid-item
          .form__label Адрес магазина
          - if @shop.errors[:city][0]
            .inputbox.inputbox_error
              = f.text_field :formatted_address, class: "inputbox__input"
              .inputbox__error
                = "Неверный формат адреса"
          - else
            .inputbox
              = f.text_field :formatted_address, class: "inputbox__input", placeholder: "Введите город", :name => "formatted_address", "data-geo" => "formatted_address", id: "formatted_address"

          .details style="display:none"
            = f.hidden_field :city, name: "shop[city]", :id => "shop_city", "data-geo" => "locality"
            = f.hidden_field :country, name: "shop[country]", :id => "shop_country", "data-geo" => "country"
            = f.hidden_field :state, name: "shop[state]", :id => "shop_state", "data-geo" => "administrative_area_level_1"
            = f.hidden_field :lat, name: "shop[lat]", :id => "shop_lat", "data-geo" => "lat"
            = f.hidden_field :lng, name: "shop[lng]", :id => "shop_lng", "data-geo" => "lng"
            = f.hidden_field :formatted_address, name: "shop[formatted_address]", :id => "shop_formatted_address", "data-geo" => "formatted_address"

    .form-section
      .grid.clearfix
        .grid-item.grip-pay.grip_inside
          .form__label Условие оплаты
          - @payment_types.each_with_index do |payment_type, index|
            .checkbox
              = check_box_tag "shop[payment_type_ids][]", payment_type.id, @shop.payment_types.map(&:id).include?(payment_type.id), class: "checkbox__input", id: "checkbox_#{index.to_s}"
              label.checkbox__label for="checkbox_#{index.to_s}"
                =< payment_type.title
        .grid-item.grid-return
          .form__label Условия возврата
          .inputbox.inputbox_type_textarea
            = f.text_area :return, class: "inputbox__input"
    .form-section
      .grid.grid_cols_3.clearfix
        .grid-item
          .form__label Куда доставляем
          = f.hidden_field :delivery_place
          #delivery_places_list.dropdown
            a.dropdown-switch.js-link href="#"
              = @shop.delivery_place.blank? ? "Куда доставляем" : @shop.delivery_place
            ul.dropdown-list.js-dropdown-list
              li В моем городе
              li Внутри страны
              li Международная доставка
      .grid-item.grid-return
        .form__label Способ доставки
        .inputbox.inputbox_type_textarea
          = f.text_area :delivery_method, class: "inputbox__input"
    .form-section
      a#submit.button.button_type_default href=""  Сохранить

javascript:
  $("#formatted_address").geocomplete({
    details: ".details",
    detailsAttribute: "data-geo"
  });

app/views/shops/error.js.erb
<% unless @shop.errors[:cover].blank? %>
  $('#cover__place').hide();
  $('#cover__errors').show();
<% end %>

<% unless @shop.errors[:title].blank? %>
  $('#shop_title').parent().addClass('inputbox_error');
  $('#shop_title_blank').show();
<% end %>

<% unless @shop.errors[:site].blank? %>
  $('#shop_site').parent().addClass('inputbox_error');
  $('#shop_site_blank').show();
<% end %>

app/views/shops/get_cities.js.erb
$("#shop_city").autocomplete({
  source: JSON.parse(('<%= @cities_from_vk %>').replace(/&quot;/g, '"')),
  messages: {
    noResults: '',
    results: function() {
      return '';
    }
  }
});

app/views/shops/show.slim
- if @shop.products.blank?
  = render 'shop_blank'
- else
  .header-top
    .layout-page
      h1.header-top__title
        = @shop.title.blank? ? "Продавец " + current_user.name : @shop.title
      - if @shop.country.present?
        span.header-top__link
          = @shop.city.to_s + ", " if @shop.city.present?
          = @shop.country

      - if current_user
        - unless @shop.user_id == current_user.id
          = link_to conversations_path(user_id: @shop.user.id), method: :post, class: "header-top__link"
            i.icon-mail
            | Связаться
      - else
        a#login_button_three.header-top__link href=""
          i.icon-mail
          | Связаться

      - if @shop.site.present?
        a.header-top__link href="http://#{@shop.site}" target="_blank"
          i.icon-site
          | Сайт
  .header-bottom
    .layout-page
      .main-pic style="background-image: url('#{image_path @shop.cover.url(:medium)}')"
      .header-bottom__btn
        = link_to "Настроить магазин", edit_shop_path(current_user.shop), class: "button button_type_default" if current_user == @shop.user
      .header-bottom__title
        |На Музточке с
        =<l @shop.created_at.to_date, format: :long
      .header-bottom__text
        - if @shop.description.present?
          = @shop.description + ' '
        - else
            | Лучшее место для покупки музыкальных инструментов
            - if @shop.city.present?
              = ', ' + @shop.city + ' '

  .layout-page.clearfix
    = form_tag shop_path(@shop), method: 'get', id: 'shop_filters_form'
      .filtering
        .filtering__count
          = count_products_of_shop(@shop.count_of_products)

        = hidden_field_tag 'main_filter',params[:main_filter]

        .filtering__buttons#shop_filtering__buttons
          .buttons-set.clearfix
            a.button.button_type_default href="" class="#{'button_active' if params[:main_filter] == "handmade"}" data-type="handmade"
              |Б/У и handmade
            a.button.button_type_default href="" class="#{'button_active' if params[:main_filter] == "new"}" data-type="new"
              |Новые
            a.button.button_type_default href=""  class="#{'button_active' if params[:main_filter].blank?}" data-type=""
              |Все

        = hidden_field_tag 'sort_by', params[:sort_by]
        .filtering__sort
          #sort_select.dropdown
            a.dropdown-switch.js-link href="#"
              - if params[:sort_by] == "newest"
                |Последние
              - elsif params[:sort_by] == "price_low_first"
                |По возрастанию цены
              - elsif params[:sort_by] == "price_high_first"
                |По убыванию цены
              - else
                |Выберите опцию
            ul.dropdown-list.js-dropdown-list
              li data-sort="newest"
                |Последние
              li data-sort="price_low_first"
                |По возрастанию цены
              li data-sort="price_high_first"
                |По убыванию цены
        .filtering__price
          .filtering-text
            | Макс. цена
            |&nbsp;
            i.icon-usd
          .inputbox
            = text_field_tag :max_price, params[:max_price], class: "inputbox__input"
        .filtering__action
          a.button.button_type_default href="" id="submit_shop_filter_form" Фильтр

      .layout-filters
        .filter-item
          .filter-item__head Категории
          = hidden_field_tag 'category', params[:category]
          = hidden_field_tag 'subcategory', params[:subcategory]
          = hidden_field_tag 'detail', params[:detail]

          ul.filter-list.filter-list_category#shop_filters_list
            - @categories.each do |category|
              li
                = link_to "", class: "link-grey", :data_id => category.id
                  .filter-list__title style="#{'color:#d37900;' if params[:category] == category.id.to_s}"
                    = category.title
                  .filter-list__count style="#{'color:#d37900;' if params[:category] == category.id.to_s}"
                    = category.products.where(:shop_id => @shop.id).count

                .wraper_subcategory#show_hover_subcategory
                  .wraper_subcategory_inner
                    ul.filter-list.filter-list_category_subcategory
                      .wraper_icon_category
                        .filter-subcategory__head
                          = category.title
                        img src="#{image_path category.iconic}"

                      - category.subcategories.where(:id => @shop.products.map(&:subcategory_id)).each do |subcategory|
                        li
                          = link_to "#", class: "link-grey", :sub_data_id => subcategory.id, :data_id => category.id
                            .filter-list__title style="#{'color:#d37900;' if params[:subcategory] == subcategory.id.to_s}"
                              = subcategory.title
                      li
                        = link_to "", :data_id => category.id
                          |Все товары
                    ul.filter-list.filter-list_category_subcategory.other
                      .filter-subcategory__head Детали и принадлежности

                      - category.details.where(:id => @shop.products.map(&:detail_id)).each do |detail|
                        li
                          = link_to "#", class: "link-grey", :det_data_id => detail.id, :data_id => category.id
                            .filter-list__title style="#{'color:#d37900;' if params[:detail] == detail.id.to_s}"
                              = detail.title



        .filter-item
          .filter-item__head Бренды
          ul.filter-list.filter-list_brands
            - @brands.each_with_index do |brand, index|
              li
                a.checkbox 
                  = check_box_tag "brands[]", brand.id, params[:brands] && params[:brands].include?(brand.id.to_s), :id => "checkbox_" + index.to_s, :class => "checkbox__input check__shop_form"
                  label.checkbox__label for="checkbox_#{index.to_s}"
                    =< brand.title
                .filter-list__count
                  = brand.products.where(:shop_id => @shop.id).count
          / = link_to "Все бренды", brands_path, class: "filter-more__link"

        .filter-item
          .filter-item__head Год выпуска
          = hidden_field_tag 'min_year', params[:min_year]
          = hidden_field_tag 'max_year', params[:max_year]
          ul.filter-list.filter-list_years#shop_list_years
            -if @products.in_list?('>', 2011)
              li
                a.link-grey href="" data-min="2011" style="#{'color:#d37900;' if params[:min_year] == '2011'}"
                  .filter-list__title с 2011
            -if @products.in_list?(2001, 2010)
              li
                a.link-grey href="" data-min="2001" data-max="2010" style="#{'color:#d37900;' if params[:min_year] == '2001'}"
                  .filter-list__title 2001 - 2010
            -if @products.in_list?(1991, 2000)
              li
                a.link-grey href="" data-min="1991" data-max="2000" style="#{'color:#d37900;' if params[:min_year] == '1991'}"
                  .filter-list__title 1991 - 2000
            -if @products.in_list?(1981, 1990)
              li
                a.link-grey href="" data-min="1981" data-max="1990" style="#{'color:#d37900;' if params[:min_year] == '1981'}"
                  .filter-list__title 1981 - 1990
            -if @products.in_list?(1971, 1980)
              li
                a.link-grey href="" data-min="1971" data-max="1980" style="#{'color:#d37900;' if params[:min_year] == '1971'}"
                  .filter-list__title 1971 - 1980
            -if @products.in_list?(1961, 1970)
              li
                a.link-grey href="" data-min="1961" data-max="1970" style="#{'color:#d37900;' if params[:min_year] == '1961'}"
                  .filter-list__title 1961 - 1970
            -if @products.in_list?(1950, 1960)
              li
                a.link-grey href="" data-min="1950" data-max="1960" style="#{'color:#d37900;' if params[:min_year] == '1950'}"
                  .filter-list__title 1950 - 1960
            -if @products.in_list?('<', 1950)
              li
                a.link-grey href="" data-max="1950" style="#{'color:#d37900;' if params[:max_year] == '1950'}"
                .filter-list__title до 1950
          = link_to "#", :class => "filter-more__link", id: "all_years"
            .filter-list__title
              | Все года

        = render 'shared/popular'

      .layout-bricks
        .bricks.js-masonry
          - if @products.present?
            - @products.each do |product|
              = link_to product, class: "brick-item"
                - if product.photos.present?
                  = image_tag product.photos.first.image(:large), class: "brick-item__photo", alt: "#{product.title}", title: "Купить #{product.title}"
                .brick-item__bottom
                  .brick-item__title
                    = product.title
                  .brick-item__price
                    =< price(product.price)
          - else
            .nosearch По вашему запросу ничего не найдено

        = paginate @products, params: request.query_parameters

app/views/shops/success.js.erb
$('#flash__open').fadeIn(500);
$('.inputbox').removeClass('inputbox_error');
$('#cover__errors').hide();
$('#shop_title_blank').hide();
$('#shop_site_blank').hide();
$("html, body").animate({ scrollTop: 0 }, "slow");