config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :confirmations => "confirmations",
                                       :passwords => "passwords",
                                       :sessions => "sessions" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'
  get '/triggers_test/', :to => 'triggers_test#triggers_test'

  root 'home#index'
  resources :brands
  resources :users, except: [:destroy, :index] do
    member do
      get :favorites
      get :goods
      patch :set_password
      delete :destroy_social_account
      delete :delete_avatar
    end
  end
  resources :products, except: [:index] do
    collection do
      post 'get_subcategories'
      post 'get_details'
      get 'fake_typing_titles'
      get 'dynamic_admin_subcategory'
    end
  end

  resources :categories, only: [:show]

  resources :photos, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

  resources :shops, :controller => :shops do
    collection do
      post :update_shop_cover
      get :delete_shop_cover
    end
  end

  resources :promo_items, only: [:create, :update, :show] do
    member do
      get 'notify'
    end
  end

  controller :payments do
    post 'notify', as: :notify
  end

  post '/liqpay_payment' => 'payments#liqpay_payment'

  resources :conversations, only: [:index, :show, :create, :destroy]

  controller :static do
    get 'about', as: :about
    get 'condition', as: :condition
    get 'faq', as: :faq
    get 'contacts', as: :contacts
    get 'why_muzpoint', as: :why_muzpoint
    get 'how_advertising_works', as: :how_advertising_works
    get 'terms_of_use', as: :terms_of_use
  end

  resources :subscribers, :only => [:create]
  resources :feedbacks, :only => [:create]
  post 'mark_as_read',to:'messages#mark_as_read'
  resources :posts,path: :blog do
    collection do
      get 'articles'
      get 'photos'
      get 'overviews'
      get 'lessons'
    end
  end
  devise_scope :user do
    post 'session_path',to: 'sessions#path'
  end
  post '/switch_currency',to: 'switch_currency#switch'

  get 'template',to: 'xml_templates#template'
  get '/countries', to: 'countries#index', as: :countries, controller: "countries"
  get '/countries/:id', to: 'countries#show', as: :country, controller: "countries"

  get '/cities', to: 'cities#index', as: :cities, controller: "cities"
  get '/countries/:country_id/:state_id/:id', to: 'cities#show', as: :city, controller: "cities"

  get '/categories/:category_id/:id', to: 'subcategories#show', as: :subcategory, controller: "subcategories"

  get '404', :to => 'errors#page_not_found'
  get '500', :to => 'errors#server_error'
  get '/:category_id/:id', to: redirect("/categories/%{category_id}/%{id}", status: 301)
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  default_scope { order('updated_at DESC') }

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  belongs_to :product
  has_many :messages

  before_create :set_read_at_defaults

  validates :sender, :recipient, presence: true
  # validates :sender, uniqueness: { scope: :recipient }

  def user_read_at(user_id)
    if self.sender_id == user_id
      self.sender_read_at
    else
      self.recipient_read_at
    end
  end

  def count_unread(user_id)
    Message.where(:conversation_id => self.id)
           .where('created_at > ?', user_read_at(user_id))
           .where('sender_id != ?', user_id)
           .count
  end

  def sender?(user_id)
    self.sender_id == user_id
  end

  def self.find_or_create(sender_id, recipient_id)
    @conversation = nil
    unless sender_id == recipient_id
      @conversation = Conversation.where('(sender_id = :sender_id AND recipient_id = :recipient_id) OR (sender_id = :recipient_id AND recipient_id = :sender_id)', sender_id: sender_id, recipient_id: recipient_id).first
      unless @conversation
        @conversation = Conversation.create(
          :sender_id => sender_id,
          :recipient_id => recipient_id
        )
      end
    end
    @conversation
  end


  def companion_name(user)
    if sender == user
      recipient.name
    else
      sender.name
    end
  end

  def update_check(user)
    if sender?(user)
      self.update_attribute(:sender_read_at, Time.zone.now)
    else
      self.update_attribute(:recipient_read_at, Time.zone.now)
    end
  end


private

  def set_read_at_defaults
    self.sender_read_at = Time.zone.now
    self.recipient_read_at = Time.zone.now
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :sign_in_from_email

  def index
    @conversations = Conversation.where('sender_id = ? OR recipient_id = ?', current_user.id, current_user.id)
    @conversations = @conversations.where('(sender_id = ? AND show_for_sender = ?) OR (recipient_id = ? AND show_for_recipient = ?)', current_user.id, true, current_user.id, true)
    @outbox_messages = current_user.messages.where(sender_id: current_user.id)
    @inbox_messages = current_user.messages.where('messages.sender_id != ?',current_user.id)
    if params[:sentence].present?
      ids = @conversations.pluck(:id)
      cids = Message.where(conversation_id: ids).includes(:sender).
          where('messages.text ILIKE ? OR users.name ILIKE ?',
                '%' + params[:sentence] + '%',
                '%' + params[:sentence] + '%').pluck(:conversation_id)
      @conversations = @conversations.where(id: cids).page(params[:page]).per(30)
    end
  end

  def create
    @conversation = Conversation.find_or_create_by(sender_id:current_user.id, recipient_id:params[:user_id],product_id:params[:product_id])
    redirect_to @conversation
  end

  def show
    @conversation = Conversation.find(params[:id])
    gon.channel = @conversation.id.to_s
    @conversation.update_check(current_user)
    # do we need this?
    @conversation_messages = @conversation.messages.order('created_at asc')
    gon.websocketpath = Rails.env.production? ? 'muztochka.com/websocket' : (request.host_with_port + '/websocket')
    if Rails.env.production?
      gon.websocketpath = 'muztochka.com/websocket'
    elsif Rails.env.staging?
      gon.websocketpath = 'muzdot.thedigitalcrafters.com/websocket'
    else
      gon.websocketpath = request.host_with_port + '/websocket'
    end
  end

  def destroy
    @conversation = Conversation.find(params[:id])
    if @conversation.sender_id == current_user.id
      @conversation.update(show_for_sender: false)
    elsif @conversation.recipient_id == current_user.id
      @conversation.update(show_for_recipient: false)
    end
    redirect_to conversations_path
  end

  private

  def sign_in_from_email
    if params[:recipient_id]
      user = User.find(params[:recipient_id])
      if user
        sign_in user, :bypass => true
        redirect_to conversation_path(params[:id])
      else
        redirect_to root_path
      end
    end
  end

end

app/views/conversations/_message.slim
li.dialog-item
  = link_to image_tag(message.sender.avatar(:chat), :class => "dialog-item__avatar"),shop_path(message.sender.shop.slug)
  .dialog-item__text
  	= raw(message.text)
  .dialog-item__footer
  	=> link_to message.sender.name, shop_path(message.sender.shop.slug)
    .dialog-item__date
    	=< time_ago_in_words message.created_at
    .product_in_conversation
      = message.conversation.product.title if message.conversation.product

app/views/conversations/index.slim
= render 'users/profile_menu'
.layout-small
  .good-top_wrap.messages-top__wrap.clearfix
    .good-search
      = form_tag conversations_path, method: 'GET'
        .inputbox.inputbox_action_yes
          input.inputbox__input value="#{params[:sentence]}"  type="text" name='sentence'  placeholder=("Найти в сообщениях") /
          .inputbox__action
            button.link-grey type='submit' 
              i.icon-search
    .grid-item.grid-messages-top
      a.button.button_type_default href=""  Не прочитанные
      a.button.button_type_default.button_active href=""  Все
  ul.list-messages
    - @conversations.each do |conversation|
      - if conversation.messages.length > 0 && conversation.sender && conversation.recipient
        li class="#{'new_messages' if conversation.messages.first.unreaded?(current_user)}"
          = link_to conversation, :class => "message message_unread"
            .message__name = conversation.companion_name(current_user)
            .message_product_name =link_to conversation.product.title,product_path(conversation.product.id) if conversation.product
            .message__text = raw conversation.messages.first.text
            .message__date = time_ago_in_words(conversation.messages.first.created_at) + ' назад от ' + conversation.messages.first.sender.name
          = link_to conversation, method: :delete, class: "message__delete link-grey"
            i.icon-remove.link-grey data-original-title="Удалить" data-placement="top" data-toggle="tooltip" title=""
-if params[:sentence].present?
  =paginate @conversations

app/views/conversations/show.slim
script src="/ckeditor/ckeditor.js"
- if @conversation.sender_id == current_user.id or @conversation.recipient_id == current_user.id
  = render 'users/profile_menu'
  .layout-small#chat
    .dialog__wrap
      .dialog__back
        = link_to conversations_path, :class => "button button_type_default button_size_small"
          i.icon-arrow
          | Все сообщения
      .dialog__head
        => link_to 'Диалог с ' + @conversation.companion_name(current_user),shop_path(@conversation.sender.shop.slug)
        = link_to @conversation, method: :delete, :class => "link-grey"
          i.icon-remove data-original-title="Удалить" data-placement="top" data-toggle="tooltip" title=""
      ul.list-dialogs
      	- @conversation_messages.each do |message|
      		= render partial: 'message', locals: { message: message }
      form id="message_form" action=""
        input name="sender_id" value="#{@conversation.id}" id="conversation_id" type="hidden"
        -if @conversation.recipient_id == current_user.id
          input name="recipient_id" value="#{@conversation.sender_id}" id="recipient_id" type="hidden"
        -else
          input name="recipient_id" value="#{@conversation.recipient_id}" id="recipient_id" type="hidden"
        .form__row
          /.inputbox.inputbox_type_textarea
          textarea.inputbox__input cols="30" id="send_input" name="send_msg" placeholder=("Ваше сообщение") rows="10"
        .form__row
          input.button.button_type_default type="submit" value=("Отправить сообщение") id="send_button"