config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :confirmations => "confirmations",
                                       :passwords => "passwords",
                                       :sessions => "sessions" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'
  get '/triggers_test/', :to => 'triggers_test#triggers_test'

  root 'home#index'
  resources :brands
  resources :users, except: [:destroy, :index] do
    member do
      get :favorites
      get :goods
      patch :set_password
      delete :destroy_social_account
      delete :delete_avatar
    end
  end
  resources :products, except: [:index] do
    collection do
      post 'get_subcategories'
      post 'get_details'
      get 'fake_typing_titles'
      get 'dynamic_admin_subcategory'
    end
  end

  resources :categories, only: [:show]

  resources :photos, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

  resources :shops, :controller => :shops do
    collection do
      post :update_shop_cover
      get :delete_shop_cover
    end
  end

  resources :promo_items, only: [:create, :update, :show] do
    member do
      get 'notify'
    end
  end

  controller :payments do
    post 'notify', as: :notify
  end

  post '/liqpay_payment' => 'payments#liqpay_payment'

  resources :conversations, only: [:index, :show, :create, :destroy]

  controller :static do
    get 'about', as: :about
    get 'condition', as: :condition
    get 'faq', as: :faq
    get 'contacts', as: :contacts
    get 'why_muzpoint', as: :why_muzpoint
    get 'how_advertising_works', as: :how_advertising_works
    get 'terms_of_use', as: :terms_of_use
  end

  resources :subscribers, :only => [:create]
  resources :feedbacks, :only => [:create]
  post 'mark_as_read',to:'messages#mark_as_read'
  resources :posts,path: :blog do
    collection do
      get 'articles'
      get 'photos'
      get 'overviews'
      get 'lessons'
    end
  end
  devise_scope :user do
    post 'session_path',to: 'sessions#path'
  end
  post '/switch_currency',to: 'switch_currency#switch'

  get 'template',to: 'xml_templates#template'
  get '/countries', to: 'countries#index', as: :countries, controller: "countries"
  get '/countries/:id', to: 'countries#show', as: :country, controller: "countries"

  get '/cities', to: 'cities#index', as: :cities, controller: "cities"
  get '/countries/:country_id/:state_id/:id', to: 'cities#show', as: :city, controller: "cities"

  get '/categories/:category_id/:id', to: 'subcategories#show', as: :subcategory, controller: "subcategories"

  get '404', :to => 'errors#page_not_found'
  get '500', :to => 'errors#server_error'
  get '/:category_id/:id', to: redirect("/categories/%{category_id}/%{id}", status: 301)
end

app/views/shared/_deletion.slim
#delet_popup.popup.popup_open
  .int_popup__wrap
    = form_tag '', method: 'DELETE', class: 'popup__content'
      .int_popup_title Почему удаляете товар?
      .block_int_button
        - @product_deletion_reasons.each do |reason|
          label.button.button_type_default.reason-button for="reason_#{reason.id}"
            input type='radio' name='reason_id' id="reason_#{reason.id}" value=reason.id
            span= reason.name_ru
        a.button.button_type_default.delete_abort Отмена

app/views/shared/_feedback.slim
.popup-overlay
#feedback_popup.popup.popup_open
  .popup__wrap
    a.popup__close
      i.icon-cancel
    .popup__content
      .popup__head
        i.icon-mail
        =< "Сообщение"
      = render :partial => "feedbacks/form", :locals => { feedback: @footer_feedback}

#feedback_success.popup.popup_open
  .popup__wrap_sent
    a.popup__close
      i.icon-cancel
    .popup__content_sent
      .popup__head_sent
        |  Спасибо, уже читаем!

app/views/shared/_header.slim
.header
  / a#delet_button href="#" style="width: 10px;height: 10px; background-color: #000; float: left;"
  .layout-page
    = link_to root_path, :class => "header-logo" do
      = image_tag "logo/logo.svg", class: "header-logo__img"
    .header-search
      = form_tag root_path, :method => 'get', id: 'products_search' do
        .inputbox.inputbox_style_dark.inputbox_action_yes
          = text_field_tag :search, params[:search], class: "inputbox__input header_search", placeholder: "Поиск"
          .inputbox__action
            a.link-grey href=""
              i.icon-search id="submit_search"
    - unless user_signed_in?
      ul.header-menu
        li
          .header-button
            .blogs Блог
            a.button.button_type_default id="#{'login_button_two' if !current_user}" href=""
              i.icon-plus
              span.button__text
              |  Продать
        li
          a href="" id="register_button"  регистрация
        li
          a href="" id="login_button"  Вход
    - else
      .header-button
        - if current_user.email.blank?
          a#sale_button.button.button_type_default
            i.icon-plus
          span.button__text Продать
        - else
          .blogs Блог
          = link_to new_product_path, class: 'button button_type_default'
            i.icon-plus
            span.button__text Продать
      .header-user
        .user
          - if @new_messages > 0
            span.user-notify = @new_messages
          a.control-user
            span.user-avatar
              = image_tag current_user.avatar(:thumb), class: "user-avatar__img"
            span.arrow

          = render 'shared/header_menu'

app/views/shared/_header_menu.slim
ul.user-menu
  li
    .user-menu__top
      .user-menu__name
        = current_user.name
      = link_to "Перейти в магазин", shop_path(current_user.shop), class: "user-menu__store"
  li
    = link_to edit_user_path(current_user), class: "user-menu__link"
      i.icon-user
      | Аккаунт
  li
    = link_to edit_shop_path(current_user.shop), class: "user-menu__link"
      i.icon-gear
      | Настройки магазина
  li
    = link_to goods_user_path(current_user), class: "user-menu__link"
      i.icon-tag
      | Товары
  li
    = link_to conversations_path, class: "user-menu__link",id:'unread_msgs'
      i.icon-mail
      | Сообщения
      span.user-menu__count style="margin-left:6px;"  = @new_messages if @new_messages > 0
  li
    = link_to favorites_user_path(current_user), :class => "user-menu__link"
      i.icon-heart
      | Избранное
  li
    = link_to "Выйти", destroy_user_session_path, :method => :delete, class: "user-menu__link log_out"

app/views/shared/_login.slim
.popup-overlay
#login_popup.popup.popup_open
  .popup__wrap
    a.popup__close
      i.icon-cancel
    .popup__content
      = image_tag "logo/logo.svg"
      = form_tag user_session_path, :remote => true, authenticity_token: true, :class => "form form_login"
        .form__row
          .inputbox.inputbox_style_dark
            = text_field_tag "user[email]", "",:class => "inputbox__input", :placeholder => "Электронная почта", :autocomplete => :off
        .form__row
          .inputbox.inputbox_style_dark
            = password_field_tag "user[password]", "",:class => "inputbox__input", :placeholder => "Пароль"
        .form__row
          #log_error_messages.popup__error style="display:none"
            |Неверное имя пользователя или пароль
        .form__row.clearfix
          = submit_tag "Войти", :class => "button button_type_default log_in"
          #recovery_button.form__more
            a href=""  Забыли пароль?
      .login-dont
        | Нет аккаунта?
        a href="" id="register_popup_button"
          =< "Зарегистрируйтесь"
      .social-login.social-login_popup
        .social-login__head Войти с помощью
        .clearfix
          .social-login__item
            = link_to "Вконтакте", user_omniauth_authorize_path(:vkontakte), class: "button button_type_vk button_block"
          .social-login__item
            = link_to "Facebook", user_omniauth_authorize_path(:facebook), class: "button button_type_fb button_block"

app/views/shared/_paginator.slim
ul.pagination.clearfix
  - if @page > 1
    li
      = link_to 'Предыдущая', params.merge(:page => @page - 1)
  - if @pages.times.count > 1

    - if @pages > 6
      - if params[:page]
        - if @page >= 4
          li
            = link_to "1", params.merge(:page => 1)

          - if @page > 4
            li
              a
                |...
          li
            = link_to (@page - 2).to_s, params.merge(:page => (@page - 2))
          li
            = link_to (@page - 1).to_s, params.merge(:page => (@page - 1))

          - if @page < @pages
            li._current
              = link_to params[:page], params.merge(:page => params[:page])

          - if @page <= @pages - 2
            li
              = link_to (@page + 1).to_s, params.merge(:page => (@page + 1))

          - if @page <= @pages - 3
            li
              = link_to (@page + 2).to_s, params.merge(:page => (@page + 2))

          - if @pages.to_i - 3 > @page
            li
              a
                |...
          li class="#{'_current' if @pages == @page}"
            = link_to @pages, params.merge(:page => @pages)

        - else
          - @pages.times do |page|
            - if page <= 4
              li class="#{'_current' if page + 1 == @page}"
                = link_to page + 1, params.merge(:page => page + 1)
          li
            a
              |...
          li
            = link_to @pages, params.merge(:page => @pages)

      -else
        li._current
          = link_to "1", params.merge(:page => 1)
        li
          = link_to "2", params.merge(:page => 2)
        li
          = link_to "3", params.merge(:page => 3)
        li
          = link_to "4", params.merge(:page => 4)
        li
          = link_to "5", params.merge(:page => 5)
        li
          a
            |...
        li
          = link_to @pages - 1 , params.merge(:page => @pages - 1)
        li
          = link_to @pages, params.merge(:page => @pages)

    - else
      - @pages.times do |page|
        li class="#{'_current' if page + 1 == @page}"
          = link_to page + 1, params.merge(:page => page + 1)


  - if @page < @pages
    li
      = link_to 'Следующая', params.merge(:page => @page + 1)

app/views/shared/_password_edit.slim
#password_edit_popup.popup.popup_open
  .popup__wrap
    a.popup__close
      i.icon-cancel
    .popup__content
      = image_tag "logo/logo.svg"
      = form_for current_user, :html => { :remote => true, :id => "password_changing_form" } do |user|
        .form__row
          .form__label
            |Текущий пароль
          .inputbox.inputbox_style_dark
            = user.password_field :current_password, class: "inputbox inputbox__input"
        .form__row
          #current_password_messages.popup__error style="display:none"
            | Неверный пароль
          .form__label
            |Новый пароль
          .inputbox.inputbox_style_dark
            = user.password_field :password, class: "inputbox inputbox__input", :placeholder => "Введите пароль (мин. 8 символов)"

        .form__row.clearfix
          a#password_save.button.button_type_default href="" Сохранить

app/views/shared/_password_ok.slim
#password_edit_popup.popup.popup_open style="display:block"
  .popup__wrap
    = link_to root_path, :class => "popup__close"
      i.icon-cancel
    .popup__content
      = image_tag "logo/logo.svg"
    .form
      .form__row
        .form__label
          |Пароль успешно изменен!

app/views/shared/_password_recovery.slim
#recovery_popup.popup.popup_open
  .popup__wrap
    a.popup__close
      i.icon-cancel
    .popup__content
      = image_tag "logo/logo.svg"
      = form_tag user_password_path, class: "form_reg", remote: true do
        .form__row
          .form__label
            |Восстановить пароль
            i.icon-info data-toggle="tooltip" data-placement="top" title="" data-original-title="На ваш электронный адрес будет отправлена инструкция по востановлению пароля"
          .inputbox.inputbox_style_dark
            = text_field_tag "user[email]", '', class: "inputbox__input", placeholder: "Электронная почта"
        .form__row
          #recovery_error_messages.popup__error style="display:none"
            | E-mail не зарегистрирован
        .form__row.clearfix
          = submit_tag "Отправить",  class: "button button_type_default", data: { "disable-with" => "Отправляю ..." }
          .step-back
            a.link-grey href="" id="recovery_popup_back_button"
              |Назад
        .form__row.clearfix
          .login-dont
            | Нет аккаунта?
            a href="" id="register_popup_button_two"
              =< "Зарегистрируйтесь"

app/views/shared/_popular.slim
.filter-item.add
  .filter-item__head.add-title Популярное
  ul
    - Product.includes(:photos).most_hit(1.month.ago, 3).each do |product|
      li.add-item
        - if product.photos.present?
          = image_tag product.photos.first.image(:thumb), class: "add-pic", alt: "#{product.title}", title: "Купить #{product.title}"
        .hide-box
          = link_to product, :class => "add-link" do
            = truncate product.title, length: 12

app/views/shared/_promo.slim
- if @promo.present?
  - if @promo.count == 1
    .layout-bricks.bricks-premium
      .bricks-premium__title
        h2
          | Премиум контент
      .bricks.js-masonry-promo

        = link_to how_advertising_works_path, class: "brick-item cap"
          = image_tag "icon/promo1.png" 
          span Как работает реклама на Музточке
        = link_to how_advertising_works_path, class: "brick-item cap"
          = image_tag "icon/promo2.png" 
          span Как работает реклама на Музточке

        = link_to @promo[0], class: "brick-item item_promo"
          - if @promo[0].photos.present?
            = image_tag @promo[0].photos.first.image(:promo), class: "brick-item__photo", alt: "#{@promo[0].title}", title: "Купить #{@promo[0].title}"
          .brick-item__bottom
            .brick-item__title
              = truncate @promo[0].title, length: 55 ,separator:''
            .brick-item__price
              =< price(@promo[0].price)

  - elsif @promo.count == 2
    .layout-bricks.bricks-premium
      .bricks-premium__title
        h2
          | Премиум контент
      .bricks.js-masonry-promo

        = link_to how_advertising_works_path, class: "brick-item cap"
          = image_tag "icon/promo1.png" 
          span Как работает реклама на Музточке
        - @promo.take(2).each do |product|
          = link_to product, class: "brick-item item_promo"
            - if product.photos.present?
              = image_tag product.photos.first.image(:promo), class: "brick-item__photo", alt: "#{product.title}", title: "Купить #{product.title}"
            .brick-item__bottom
              .brick-item__title
                = truncate product.title, length: 50, separator: ''
              .brick-item__price
                =< price(product.price)


  - elsif @promo.count > 2
    .layout-bricks.bricks-premium
      .bricks-premium__title
        h2
          | Премиум контент
      .bricks.js-masonry-promo
        - @promo.each do |product|
          = link_to product, class: "brick-item item_promo"
            - if product.photos.present?
              = image_tag product.photos.first.image(:promo), class: "brick-item__photo", alt: "#{product.title}", title: "Купить #{product.title}"
            .brick-item__bottom
              .brick-item__title
                = truncate product.title, length: 50, separator: ''
              .brick-item__price
                =< price(product.price)

- else
  .layout-bricks.bricks-premium
    .bricks-premium__title
      h2
        | Премиум контент
    .bricks.js-masonry-promo
      = link_to how_advertising_works_path, class: "brick-item cap"
        = image_tag "icon/promo1.png" 
        span Как работает реклама на Музточке
      = link_to how_advertising_works_path, class: "brick-item cap"
        = image_tag "icon/promo2.png" 
        span Как работает реклама на Музточке
      = link_to how_advertising_works_path, class: "brick-item cap"
        = image_tag "icon/promo3.png" 
        span Как работает реклама на Музточке

app/views/shared/_register.slim
#register_popup.popup.popup_open
  .popup__wrap
    a.popup__close
      i.icon-cancel
    .popup__content
      = image_tag "logo/logo.svg"
      = form_for User.new, :html => {:autocomplete => "off"}, :remote => true do |f|
        .form__row
          .form__label Новый аккаунт
        .form__row
          .inputbox.inputbox_style_dark
            = f.text_field :email, class: "inputbox__input", placeholder: 'Электронная почта', 'data-validation' => :required, 'data-validation-error-msg' => 'Введите e-mail'
        .form__row
          #reg_error_messages.popup__error style="display:none"
            | Некорректный или занятый e-mail
        / .form__row
        /   .inputbox.inputbox_style_dark
        /     = f.password_field :password, class: "inputbox__input", placeholder: "Пароль"
        .form__row
          .submit__wrap.clearfix
            = f.submit "Готово", class: "input button button_type_default"
            .form__more
              | Есть аккаунт?
              a href="" id="login_popup_button" Войдите
      .social-login.social-login_popup
        .social-login__head Создать новый аккаунт с помощью
        .clearfix
          .social-login__item
            = link_to "Вконтакте", user_omniauth_authorize_path(:vkontakte), class: "button button_type_vk button_block"
          .social-login__item
            = link_to "Facebook", user_omniauth_authorize_path(:facebook), class: "button button_type_fb button_block"

app/views/shared/_subscribe.slim
.popup-overlay
#subscribe_popup.popup.popup_open
  .popup__wrap_sent
    a.popup__close
      i.icon-cancel
    .popup__content_sent
      .popup__head_sent
        h4
          |  Спасибо. Подписка оформлена

app/views/shared/_switch_currency.slim
#currency_popup.popup.popup_open
  .popup__wrap
    a.popup__close
      i.icon-cancel
    .popup__content
      .choose-text
        |Выберите валюту
    = form_tag switch_currency_path,class:'choose-form' do
      input type="radio" name="currency" value="uah" id="UAH"
        label for="UAH"class=(currency('uah')) ₴ UAH Украинская гривна
        input type="radio" name="currency" value="rub" id="RUB"
        label for="RUB" class=(currency('rub')) ₽ RUB Российский рубль
        input type="radio" name="currency" value="usd" id="USD"
        label for="USD" class=(currency('usd')) $ USD United States Dollar
        input type="radio" name="currency" value="eur" id="EUR"
        label for="EUR" class=(currency('eur')) € EUR Сurrency of the eurozone
      = submit_tag 'Сохранить',id:'change_currency'