config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :confirmations => "confirmations",
                                       :passwords => "passwords",
                                       :sessions => "sessions" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'
  get '/triggers_test/', :to => 'triggers_test#triggers_test'

  root 'home#index'
  resources :brands
  resources :users, except: [:destroy, :index] do
    member do
      get :favorites
      get :goods
      patch :set_password
      delete :destroy_social_account
      delete :delete_avatar
    end
  end
  resources :products, except: [:index] do
    collection do
      post 'get_subcategories'
      post 'get_details'
      get 'fake_typing_titles'
      get 'dynamic_admin_subcategory'
    end
  end

  resources :categories, only: [:show]

  resources :photos, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

  resources :shops, :controller => :shops do
    collection do
      post :update_shop_cover
      get :delete_shop_cover
    end
  end

  resources :promo_items, only: [:create, :update, :show] do
    member do
      get 'notify'
    end
  end

  controller :payments do
    post 'notify', as: :notify
  end

  post '/liqpay_payment' => 'payments#liqpay_payment'

  resources :conversations, only: [:index, :show, :create, :destroy]

  controller :static do
    get 'about', as: :about
    get 'condition', as: :condition
    get 'faq', as: :faq
    get 'contacts', as: :contacts
    get 'why_muzpoint', as: :why_muzpoint
    get 'how_advertising_works', as: :how_advertising_works
    get 'terms_of_use', as: :terms_of_use
  end

  resources :subscribers, :only => [:create]
  resources :feedbacks, :only => [:create]
  post 'mark_as_read',to:'messages#mark_as_read'
  resources :posts,path: :blog do
    collection do
      get 'articles'
      get 'photos'
      get 'overviews'
      get 'lessons'
    end
  end
  devise_scope :user do
    post 'session_path',to: 'sessions#path'
  end
  post '/switch_currency',to: 'switch_currency#switch'

  get 'template',to: 'xml_templates#template'
  get '/countries', to: 'countries#index', as: :countries, controller: "countries"
  get '/countries/:id', to: 'countries#show', as: :country, controller: "countries"

  get '/cities', to: 'cities#index', as: :cities, controller: "cities"
  get '/countries/:country_id/:state_id/:id', to: 'cities#show', as: :city, controller: "cities"

  get '/categories/:category_id/:id', to: 'subcategories#show', as: :subcategory, controller: "subcategories"

  get '404', :to => 'errors#page_not_found'
  get '500', :to => 'errors#server_error'
  get '/:category_id/:id', to: redirect("/categories/%{category_id}/%{id}", status: 301)
end

app/models/category.rb
class Category < ActiveRecord::Base
  before_save :set_seo

  has_many :subcategories, dependent: :destroy
  has_many :details, dependent: :destroy
  has_many :products, dependent: :destroy

  accepts_nested_attributes_for :subcategories, allow_destroy: true
  accepts_nested_attributes_for :details, allow_destroy: true

  extend FriendlyId
  friendly_id :title, use: :slugged
  validates :title, :presence => true

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  has_attached_file :image, :styles => { :large => "1920x220#", :thumb => "284x44#" },
                            default_style: :original, :default_url =>  "bg/bg_filter.jpg"
  validates_attachment :image,
                        content_type: { content_type: /^image\/(jpeg|jpg|png|gif)$/ },
                        size: { in: 0..5.megabytes }

  default_scope { order('position') }

  def set_seo
    if self.seo_title.blank?
      self.seo_title = self.title + " купить по цене от 50$ на muztochka.com"
    end

    if self.seo_description.blank?
      self.seo_description = "Хочешь купить " + self.title + "?" + " " + "Покупай на Музточке: б/у и новые " + self.title + ". Muztochka.com - товары напрямую от продавцов. Выгодные цены. Удобный сервис."
    end
  end

  def iconic
    case self.id
      when 1
        "icon/icons_0015_electric.png"
      when 2
        "icon/icons_0014_pedals.png"
      when 3
        "icon/icons_0013_amps.png"
      when 4
        "icon/icons_0012_acoustic.png"
      when 5
        "icon/icons_0011_acsessories.png"
      when 6
        "icon/icons_0010_bass.png"
      when 7
        "icon/icons_0009_drums.png"
      when 8
        "icon/icons_0008_wind.png"
      when 9
        "icon/icons_0007_orchestra.png"
      when 10
        "icon/icons_0006_harp.png"
      when 11
        "icon/icons_0005_folk.png"
      when 12
        "icon/icons_0004_keys.png"
      when 13
        "icon/icons_0003_dj.png"
      when 14
        "icon/icons_0002_sound.png"
      when 15
        "icon/icons_0001_lights.png"
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.friendly.find(params[:id])

    if params[:page] == '1'
      redirect_to @category, :status => 301
    end

    @brands = Brand.where(id: @category.products.pluck(:brand_id)).take(12)
    @categories = Category.all.includes(:subcategories)

    @products = @category.products
                         .by_search(params[:search])
                         .by_category(params[:category])
                         .by_subcategory(params[:subcategory])
                         .by_detail(params[:detail])
                         .by_brands(params[:brands])
                         .by_min_year(params[:min_year])
                         .by_max_year(params[:max_year])
                         .by_main_filter(params[:main_filter])
                         .by_sort(params[:sort_by])
                         .by_max_price(params[:max_price])
                         .page(params[:page])
                         .per(30)

    @promo = @category.products
                      .joins(:promo_items)
                      .where('promo_items.status = ? AND promo_items.view_count > ?', 'success', 0)
                      .by_brands(params[:brands])
                      .sample(3)

    set_seo(@category)
  end
end

app/views/categories/_product.slim
= link_to product, class: "brick-item"
  - unless product.photos.blank?
    = image_tag product.photos.first.image(:large), class: "brick-item__photo", alt: "#{product.title}", title: "Купить #{product.title}"
  .brick-item__bottom
    .brick-item__title
      = product.title
    .brick-item__price
      =< price(product.price)

app/views/categories/show.slim
- if params[:notice] == 'ok'
  .flash-message id="flash__open"
    .flash-message__inner
      | Пароль успешно изменен
      a.flash-message__close id="flash__close"
        i.icon-cancel
- if @category && @category.image_file_name.present?
  .page-top_filter style="background: url('#{image_path @category.image(:large)}')"
    .layout-page
      .page-top__text

- else
  .page-top_filter
    .layout-page
      .page-top__text

.layout-page.clearfix
  = form_tag @category, method: 'get', id: 'filter_form'
    = hidden_field_tag 'main_filter', params[:main_filter]
    = hidden_field_tag 'detail', params[:detail]
    = hidden_field_tag 'min_year', params[:min_year]
    = hidden_field_tag 'max_year', params[:max_year]

    .filter_by_category
      - if @category
        .filter-item__header
          h1
            = @category.title

      .collect_filter_form

        - if params[:main_filter].present?
          - case params[:main_filter]
            - when "handmade"
              a.sub_params#main_submit  href=""
                = "Б/У и Handmade"
            - when "new"
              a.sub_params#main_submit  href=""
                = "Новые товары"

        - if params[:subcategory].present?
          a.sub_params#subcat_submit href="" sub_data_id="#{params[:subcategory]}"
            = Subcategory.find(params[:subcategory]).title

        - if params[:detail].present?
          a.sub_params#detail_submit href="" det_data_id="#{params[:detail]}"
            = Detail.find(params[:detail]).title

        - if params[:min_year].present?
          a.sub_params#min_year_submit href=""
            = "c "
            = params[:min_year]

        - if params[:max_year].present?
          a.sub_params#max_year_submit href=""
            = "по "
            = params[:max_year]

        .brand_params
          - if params[:brands].present?
            - params[:brands].each do |b|
              a.sub_params href="" brand-id="#{b}"
                = Brand.find_by_id(b).title


      - if @category
        - if params[:main_filter].present? or params[:subcategory].present? or params[:detail].present? or params[:min_year].present? or params[:max_year].present? or params[:brands].present?
          = link_to "Сбросить все", @category, class: "reset_category"
      .description_filter
        - if @category && @category.text
          = @category.text



    .filtering.filtering_type_index
      .page-filtering.filtering__buttons
        .buttons-set.clearfix
          a.button.button_type_default href="" class="#{'button_active' if params[:main_filter] == "handmade"}" data-type="handmade"
            |Б/У и handmade
          a.button.button_type_default href="" class="#{'button_active' if params[:main_filter] == "new"}" data-type="new"
            |Новые товары
          a.button.button_type_default href=""  class="#{'button_active' if params[:main_filter].blank?}" data-type=""
            |Все
    - if params[:search]
      - if @products.count > 0
        .result_name
          |Найдено по запросу
          =< " “"
          = params[:search]
          = "”"

    .layout-filters
      .filter-item
        .filter-item__head Категории
        ul.filter-list.filter-list_category
          - @categories.each do |category|
            li
              = link_to category_path(category), class: "link-grey"
                .filter-list__title style="#{'color:#d37900;' if @category && @category.id == category.id}"
                  = category.title
                .filter-list__count style="#{'color:#d37900;' if @category && @category.id == category.id}"
                  =< category.products.count

              - unless category.title == "Прочее"
                .wraper_subcategory#show_hover_subcategory
                  ul.filter-list.filter-list_category_subcategory
                    .wraper_icon_category
                      .filter-subcategory__head
                        = category.title
                        = link_to "Смотреть все", category
                      img src="#{image_path category.iconic}"

                    - category.subcategories.each do |subcategory|
                      li
                        = link_to subcategory_path(subcategory.category, subcategory), class: "link-grey"
                          .filter-list__title style="#{'color:#d37900;' if params[:subcategory] == subcategory.id.to_s}"
                            = subcategory.title
                          .filter-list__count style="#{'color:#d37900;' if params[:subcategory] == subcategory.id.to_s}"
                            =< subcategory.products.size

                  - unless category.title == "Аксессуары & Разное"
                    ul.filter-list.filter-list_category_subcategory.other id="details-list"
                      .filter-subcategory__head Детали и принадлежности

                      - category.details.each do |detail|
                        li
                          = link_to "#", class: "link-grey", :det_data_id => detail.id, :data_id => detail.category.slug
                            .filter-list__title style="#{'color:#d37900;' if params[:detail] == detail.id.to_s}"
                              = detail.title
                            .filter-list__count style="#{'color:#d37900;' if params[:detail] == detail.id.to_s}"
                              =< detail.products.size

      .filter-item
        .filter-item__head Бренды
        ul.filter-list.filter-list_brands
          - @brands.each_with_index do |brand, index|
            li
              a.checkbox href="#" id="brand-id-#{brand.id}"
                = check_box_tag "brands[]", brand.id, params[:brands] && params[:brands].include?(brand.id.to_s), :id => "checkbox_" + brand.id.to_s, :class => "checkbox__input collect__form"
                label.checkbox__label for="checkbox_#{brand.id.to_s}"
                  =< brand.title
        = link_to "Все бренды", brands_path, class: "filter-more__link"

      .filter-item
        .filter-item__head Год выпуска
        ul.filter-list.filter-list_years
          li
            a.link-grey href="" data-min="2011" style="#{'color:#d37900;' if params[:min_year] == '2011'}"
              .filter-list__title с 2011
          li
            a.link-grey href="" data-min="2001" data-max="2010" style="#{'color:#d37900;' if params[:min_year] == '2001'}"
              .filter-list__title 2001 - 2010
          li
            a.link-grey href="" data-min="1991" data-max="2000" style="#{'color:#d37900;' if params[:min_year] == '1991'}"
              .filter-list__title 1991 - 2000
          li
            a.link-grey href="" data-min="1981" data-max="1990" style="#{'color:#d37900;' if params[:min_year] == '1981'}"
              .filter-list__title 1981 - 1990
          li
            a.link-grey href="" data-min="1971" data-max="1980" style="#{'color:#d37900;' if params[:min_year] == '1971'}"
              .filter-list__title 1971 - 1980
          li
            a.link-grey href="" data-min="1961" data-max="1970" style="#{'color:#d37900;' if params[:min_year] == '1961'}"
              .filter-list__title 1961 - 1970
          li
            a.link-grey href="" data-min="1950" data-max="1960" style="#{'color:#d37900;' if params[:min_year] == '1950'}"
              .filter-list__title 1950 - 1960
          li
            a.link-grey href="" data-max="1950" style="#{'color:#d37900;' if params[:max_year] == '1950'}"
              .filter-list__title до 1950
        = link_to "#", :class => "filter-more__link", id: "all_years"
          .filter-list__title
            | Все года
      = render 'shared/popular'

  = render 'shared/promo'
  .layout-bricks
    - if @products.count > 0
      .bricks.js-masonry
        - @products.each do |product|
          = link_to product, class: "brick-item"
            - unless product.photos.blank?
              = image_tag product.photos.first.image(:large), class: "brick-item__photo", alt: "#{product.title}", title: "Купить #{product.title}"
            .brick-item__bottom
              .brick-item__title
                = product.title
              .brick-item__price
                =< price(product.price)


    - else
      .nosearch По вашему запросу ничего не найдено
    = paginate @products